server:
  port: 2001

spring:
  application:
    name: cloud-seata-order

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    alibaba:
      seata:
        tx-service-group: tx_group_springcloudx

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456


feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml