server:
  port: 8004

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloudx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

  cloud:
    zookeeper:
      connect-string: localhost:2184

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.liyi.*.entity

