server:
  port: 8401

spring:
  application:
    name: cloudx-sentinel-servers
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
#        port: 8719
      filter:
        url-patterns: /** #这里巨坑,默认配置只能拦截到1级目录

management:
  endpoints:
    web:
      exposure:
        include: '*'